apiVersion: v1
kind: Service
metadata:
  name: event-dispatcher
  labels:
    app: sk8s
    component: event-dispatcher
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    component: event-dispatcher
